env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
